### ISSUE TITLE
Update Optional Comments In Kotlin Tutorials

### ISSUE THREAD

**Issue by AdamMc331** [androidessence/androidessence.github.io#4]
https://chat.stackoverflow.com/transcript/message/37581345#37581345

**Comment by AdamMc331** [comment]
Also comment out "..." lines.

**Comment by TimCastelijns** [comment]
In AddTaskActivity, change `if (description?.text?.toString().isNullOrEmpty())` to use `isNullOrBlank()` instead, to also check if the text is not only made up of spaces

**Comment by TimCastelijns** [comment]
In tutorial part 2, change `val adapter = TaskAdapter()` in onCreate to be class var `var adapter: TaskAdapter? = TaskAdapter()` as seen in the finished code.

Or perhaps initialize it as `null`, since the initial value of `= TaskAdapter()` is not used.

**Comment by TimCastelijns** [comment]
In part 3, maybe mention that string resources for AddTaskActivity xml are not yet defined (or just hardcode them)

**Comment by TimCastelijns** [comment]
In part 4, "We’ve already marked our tasks and serializable in part 2" should perhaps be "We’ve already marked our tasks as serializable in part 2" (and->as)

**Comment by TimCastelijns** [comment]
In part 4, `adapter?.tasks = tasks` is highlighted with "Smart cast to kotlin.collections.MutableList<com.package.Task>". Maybe add a note what that means

**Comment by AdamMc331** [comment]
@TimCastelijns Regarding your comment about part 2, I think I should leave it as `val adapter = TaskAdapter()`, and then remove the setter inside of onCreate(). There's no need to do that, and there's also no need to make it optional. I will update the code this way.

**Comment by AdamMc331** [comment]
@TimCastelijns Can you look over https://github.com/androidessence/androidessence.com/pull/5 and give me a thumbs up if you like it?

**Comment by TimCastelijns** [comment]
I upthumbed it. Not sure if you get a notification for that

**Comment by AdamMc331** [comment]
I didn't, thanks! Will merge and update the site.
